
language: python

python:
  - { PATH: "{{replace(Python37, '\\', '\\\\')}}", VERSION: 3.7, DIST: std }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("%NAME_JENKINS%", project_name + "_%VERSION%_%DIST%_%NAME%"), "_venv")}}
  
install:
  - pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ jyquickhelper --extra-index-url=https://pypi.python.org/simple/
  - pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ pyquickhelper --extra-index-url=https://pypi.python.org/simple/
  - pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ pymyinstall pyensae --extra-index-url=https://pypi.python.org/simple/
  - pip install -r requirements.txt
  - pip freeze
  - pip freeze > pip_freeze.txt
before_script:
  - python -u setup.py build_ext --inplace
  - set KERAS_BACKEND=tensorflow
script:
  - { CMD: "python -u setup.py unittests -g .*MODULE.*", NAME: "UT", TIMEOUT: 2400 }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e \".*((keras)).*\"", NAME: "UT_KERAS", TIMEOUT: 7200 }
  - { CMD: "python -X faulthandler -X showrefcount -u setup.py unittests -e \".*((deep)).*\"", NAME: "UT_DEEP2", TIMEOUT: 7200 }
  - { CMD: "python -X faulthandler -u setup.py unittests -e .*MODULE.*", NAME: "UT_MODULE" }
after_script:
  - python -u setup.py bdist_wheel
  - if [ ${DIST} != "conda" and ${NAME} == "UT" ] then copy dist\*.whl {{root_path}}\..\..\local_pypi\local_pypi_server fi
documentation:
  - if [ ${NAME} == "UT" ] then python -u setup.py build_sphinx fi
  - if [ ${NAME} == "UT" ] then xcopy /E /C /I /Y _doc\sphinxdoc\build\html dist\html fi
