version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.6
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          - v2-dependencies-

      - run:
          name: Install pandoc
          command: |
                    sudo apt-get update 
                    wget https://github.com/jgm/pandoc/releases/download/2.14.1/pandoc-2.14.1-1-amd64.deb
                    sudo dpkg -i pandoc-2.14.1-1-amd64.deb

      - run:
          name: Install tex
          command: |
                    sudo apt-get install -y texlive
                    sudo apt-get install -y texlive-latex-extra
                    sudo apt-get install -y texlive-lang-french
                    sudo apt-get install -y texlive-xetex
                    sudo apt-get install -y dvipng
          
      - run:
          name: Install 7z
          command: |
                    sudo apt-get install -y p7zip-full
          
      - run:
          name: Install InkScape
          command: |
                    sudo apt-get install -y inkscape
          
      - run:
          name: Install graphviz
          command: |
                    sudo apt-get install -y graphviz

      # statsmodels setup.py requires it
      - run:
          name: install numpy
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install numpy

      - run:
          name: install torch, tensorflow
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
            pip install tensorflow

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: install tensorflow
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tensorflow_model_optimization

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: compile and build
          command: |
            . venv/bin/activate
            export PYTHONPATH=src
            python setup.py build_ext --inplace

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export PYTHONPATH=src
            python setup.py unittests

      - run:
          name: wheel
          command: |
            . venv/bin/activate
            export PYTHONPATH=src
            python setup.py bdist_wheel
            mkdir -p test-reports/dist
            cp dist/*.whl test-reports/dist
            mkdir -p test-reports/src
            cp -r  src/ensae_teaching_dl test-reports/src

      #- run:
      #    name: documentation
      #    command: |
      #      . venv/bin/activate
      #      export PYTHONPATH=src
      #      python setup.py build_sphinx
            
      #- run:
      #    name: copy documentation
      #    command: |
      #      mkdir -p test-reports/doc
      #      zip -r -9  test-reports/doc/documentation_html.zip _doc/sphinxdoc/build/html
            
      - store_artifacts:
          path: test-reports
          destination: test-reports